project/coin/forms.py
# project/coins/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, IntegerField, SelectField
from wtforms.validators import InputRequired, Email, Length, EqualTo

from project.models import Coin, Miningtype



# Form class in creating a new coin record
class CoinRegisterForm(FlaskForm):
    coin_name = StringField('name', validators=[InputRequired(), Length(min=1, max=80)])
    coin_symbol = StringField('symbol', validators=[InputRequired(), Length(min=1, max=6)])
    coin_website = StringField('website', validators=[InputRequired(), Length(min=1)])
    coin_forum = StringField('forum')
    coin_status = BooleanField('status')
    mining_name = SelectField(u'mining type', coerce=int)

    def validate(self):
        initial_validation = super(CoinRegisterForm, self).validate()
        if not initial_validation:
            return False
        coin_name = Coin.query.filter_by(coin_name=self.coin_name.data).first()
        if coin_name:
            self.name.errors.append("Coin already registered")
            return False
        return True

project/user/forms.py
# project/user/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, IntegerField
from wtforms.validators import InputRequired, Email, Length, EqualTo

from project.models import User

# A form class to change password
class ChangePasswordForm(FlaskForm):
    password = PasswordField('password', validators=[InputRequired(), Length(min=8)])
    confirm = PasswordField('Repeat password', validators=[InputRequired(), EqualTo('password', message='Passwords must match.')])

# A form class for login
class LoginForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8)])
    remember = BooleanField('remember me')

# A form class for user registration. Validates existing user through email.
class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8)])
    confirm = PasswordField('Repeat password', validators=[InputRequired(), EqualTo('password', message='Passwords must match.')])
    username = StringField('Username', validators=[InputRequired(), Length(min=1, max=80)])

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

project/wallet/forms.py
# project/wallet/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, IntegerField, SelectField
from wtforms.validators import InputRequired, Email, Length, EqualTo

from project.models import Wallet



""" A form class containing the required form fields in registering a wallet
    It validates the form input and also checks to prevent duplication.
"""
class WalletRegisterForm(FlaskForm):
    wallet_address = StringField('address', validators=[InputRequired(), Length(min=1, max=80)])
    wallet_location = StringField('location', validators=[InputRequired(), Length(min=1, max=100)])
    wallet_status = BooleanField('status')
    wallet_coinType = SelectField(u'coin', coerce=int)

    def validate(self):
        initial_validation = super(WalletRegisterForm, self).validate()
        if not initial_validation:
            return False
        wallet_address = Wallet.query.filter_by(wallet_address=self.wallet_address.data).first()
        if wallet_address:
            self.name.errors.append("Wallet already registered")
            return False
        return True

project/__init__.py
# project/__init__.py

import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_principal import Principal

#config
app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])

#initializing extensions
login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
mail = Mail(app)
db = SQLAlchemy(app)
Bootstrap(app)
Principal(app)

#blueprints
from project.main.views import main_blueprint
from project.user.views import user_blueprint
from project.coin.views import coin_blueprint
from project.wallet.views import wallet_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(coin_blueprint)
app.register_blueprint(wallet_blueprint)

# flask-login

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# error handlers
@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/coin/views.py
# project/coin/views.py

#import

from flask import render_template, Blueprint, redirect, url_for, flash, jsonify, request
from project.decorators import roles_required
from flask_login import login_required
from .forms import CoinRegisterForm
from project.models import Coin, Miningtype
from project import db
import json
from sqlalchemy.ext.declarative import DeclarativeMeta

# config
coin_blueprint = Blueprint('coin', __name__,)


# Route in creating a coin
@coin_blueprint.route('/registercoin', methods=['GET', 'POST'])
@login_required
@roles_required('admin')
def registercoin():
	form = CoinRegisterForm()
	form.mining_name.choices = [(row.id, row.mining_name) for row in Miningtype.query.all()]

	if form.validate_on_submit():
		coin = Coin(coin_name=form.coin_name.data, coin_symbol=form.coin_symbol.data, coin_website=form.coin_website.data, 
			coin_forum=form.coin_forum.data, coin_status=form.coin_status.data, miningtype_id=form.mining_name.data)
		db.session.add(coin)
		db.session.commit()

		flash('Coin successfully registered', 'success')
		return redirect(url_for('coin.registercoin'))

	return render_template('coin/registercoin.html', form=form)



# Route that checks the database if the coin already exist.
@coin_blueprint.route('/dbcoincheck', methods=['GET', 'POST'])
@login_required
@roles_required('admin')
def dbcoincheck():
	myvar = request.args["term"]
	query = db.session.query(Coin.coin_name).filter(Coin.coin_name.like('%' + str(myvar) + '%'))

	result = [coin[0] for coin in query.all()]
	return jsonify(result)

# Route that checks a web api for the coin's validity and information
@coin_blueprint.route('/webcoincheck', methods=['GET', 'POST'])
@login_required
@roles_required('admin')
def webcoincheck():
	coinNameInput = request.args["coin_name"]
	coinJson = request.args.get('https://api.coinmarketcap.com/v1/ticker/' + coinNameInput)
	query = db.session.query(Coin.coin_name).filter(Coin.coin_name.like('%' + str(coinNameInput) + '%'))

	for coin in query.all():
		if coin[0].lower() == coinNameInput.lower():
			return jsonify(" Coin has been registered.")
	return jsonify('')

project/main/views.py
# montecryoto/main/views.py

#import
from flask import Flask, render_template, Blueprint



# config
main_blueprint = Blueprint('main', __name__,)


# Route for the homepage
@main_blueprint.route('/')
def home():
	return render_template('main/index.html')

project/user/views.py
# project/user/views.py

from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from project.token import generate_confirmation_token, confirm_token
from project.models import User, Role, UserRoles, Coin
from project.email import send_email
from project.decorators import check_confirmed, roles_accepted, roles_required
from datetime import datetime
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm

user_blueprint = Blueprint('user', __name__,)


# Routes

"""
Creates the form object for user registration. On submit, creates the user record and sends
verification email to the registering user
"""
@user_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data, username=form.username.data, active=False)

        db.session.add(user)
        db.session.commit()

        role = Role.query.filter_by(name="member").first()

        user_role = UserRoles(user_id=user.id, role_id=role.id)
        db.session.add(user_role)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash('A confirmation email has been sent via email.', 'success')

        return redirect(url_for('user.unconfirmed'))                                 

    return render_template('user/signup.html', form=form)


# Route for the login process. Verifies the user password.
@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash('Welcome.', 'success')

                return redirect(url_for('user.dashboard'))                               

        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)

    return render_template('user/login.html', form=form)

# Logout route
@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('main.home'))                                       

# Route for the profile page. Can change a user password.
@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)

# Route which checks if the user has confirmed or not
@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.active:
        flash('Account already confirmed. Please login.', 'success')
        return redirect(url_for('main.home'))

    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()

    if user.email == email:
        user.active = True
        user.confirmed_at = datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account!', 'success')
        flash('Please login using your credentials.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')

    return redirect(url_for('main.home'))

# Route for unconfirmed users
@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.active:
        return redirect('main.home')
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')

# Route for resending email verification
@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


# Route for the dashboard. Displays options for the iframe on the html
@user_blueprint.route('/dashboard')
@login_required
@check_confirmed
def dashboard():
    timers = ["10 min", "20 min", "30 min", "40 min", "50 min", "60 min", "70 min", "90 min"]
    coins = Coin.query.all()
    return render_template('user/dashboard.html', username=current_user.username, timers=timers, coins=coins)

project/wallet/views.py
# project/wallet/views.py

#import

from flask import render_template, Blueprint, redirect, url_for, flash
from project.decorators import roles_required
from flask_login import login_required, current_user
from .forms import WalletRegisterForm
from project.models import Wallet, Coin
from project import db

# config
wallet_blueprint = Blueprint('wallet', __name__,)


"""
    Creates the form object to receive the entered wallet details and queries
    the db for the coin type to be presented to the user.
    Creates a wallet record for each successful submission.
"""
@wallet_blueprint.route('/registerwallet', methods=['GET', 'POST'])
@login_required
@roles_required('admin')
def registerwallet():

    form = WalletRegisterForm()
    form.wallet_coinType.choices = [(row.id, row.coin_name) for row in Coin.query.all()]

    if form.validate_on_submit():
        wallet = Wallet(wallet_address=form.wallet_address.data, wallet_location=form.wallet_location.data, 
        	wallet_status=form.wallet_status.data, coin_id=form.wallet_coinType.data, user_id=current_user.id, pay_id=1)	#payment id not finished
        db.session.add(wallet)
        db.session.commit()

        flash('Wallet successfully registered', 'success')
        return redirect(url_for('wallet.registerwallet'))                           

    return render_template('wallet/registerwallet.html', form=form)

project/templates/coin/registercoin.html
{% extends "_base.html" %}

{% block css %}
      <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
{% endblock %}

{% block content %}

<h1>Register Coin</h1>
<br>
<div id="summary"></div>

<form class="form-signin" role="form" method="post" action="{{url_for('coin.registercoin')}}">
  {{ form.csrf_token }}
  {{ form.hidden_tag() }}


  <br>
  <div class="row">
  <div class="col-xs-3">
  {{ form.coin_name(placeholder="coin name") }}
  </div>
  <div class="col-xs-3">
  <input type="text" name="coinName2" id="coinName2" placeholder="Registered coins:" style="border: 0">
  </div>
  </div>

  <br>

  <div class="row">
   <div class="col-xs-3">
  <div style="float: left" id="status"></div>
  </div>
  </div>
  <br><br><br>
  <div>
  <button class="btn btn-success" type="submit">Register</button>
  </div>
  <br><br>
</form>

{% endblock %}

{% block js %}
      <script src = "https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src = "https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>


$(document).ready(function(){
    $("button").click(function(){
          var coin_name = $("#coin_name").val();
        $.getJSON("https://api.coinmarketcap.com/v1/ticker/" + coin_name + "/", 
          function(result){
            alert(JSON.stringify(result));
            var coinJson = result; 
        })

        .done(function() { alert('getJSON request succeeded!'); })
        .fail(function(jqXHR, textStatus, errorThrown) { 
          $('#status').html('<img style="width: 30px; height: 20px; float: left" src="http://www.nus.edu.sg/identity/images/identity/logo/wrong.gif"> <p style="float: left">Incorrect coin name!</p>');
        })
        .always(function() { alert('getJSON request ended!'); });
    });
});


<!-- for every user keyup, it continually updates gives updated information to the user. This
gives the user information if the coin is already registered in the db -->

$(document).ready(function() {
  $('#coin_name').keyup(function()
  {
    var coin_name = $("#coin_name").val();
    $("#status").html('<img style="width: 50px; height: 30px" src="http://www.downgraf.com/wp-content/uploads/2014/09/01-progress.gif">');

    if (coin_name!='') {

        $.ajax({
        url: '{{ url_for("coin.webcoincheck") }}',
        dataType: 'json',
        data: $('#coin_name').serialize(),
        success: function(data) {
                  setTimeout(function()
                  {
                  delaySuccess(data);
                  }, 1000);

                   
                 }
        });

    }

    else {
      $("#status").html('');
    }


  });
});

<!-- Continually checks the coin validity through a web api This
gives the user information if the coin is valid or typed incorrectly
-->

function delaySuccess(data) {
  if (data!=''){


  $('#status').html('<img style="width: 30px; height: 20px" src="http://www.nus.edu.sg/identity/images/identity/logo/wrong.gif">'+ data);
  }
  else {

        var coin_name = $("#coin_name").val();
        $.getJSON("https://api.coinmarketcap.com/v1/ticker/" + coin_name + "/", 
          function(result){
            alert(JSON.stringify(result)); 
        })

        .done(function() { 
        })
        .fail(function(jqXHR, textStatus, errorThrown) { 
          $('#status').html('<img style="width: 30px; height: 20px; float: left" src="http://www.nus.edu.sg/identity/images/identity/logo/wrong.gif"> <p style="float: left">Incorrect coin name!</p>');
        })
        .always(function() { 
        });



  }
}


<!-- for every user keyup, it calls the route to access a web api -->

    $(document).ready(function() {
    $('#coin_name').autocomplete({
        width: 300,
        max: 10,
        delay: 100,
        minLength: 1,
        autoFocus: true,
        cacheLength: 1,
        scroll: true,
        highlight: false,
        position: { my : "left top", at: "left bottom", of: "#coinName2" },
        select: function( event, ui ) {
          return false;
        },
        source: function(request, response) {
            $.ajax({
                url: '{{ url_for("coin.dbcoincheck") }}',
                dataType: "json",
                data: {
                  term: $('#coin_name').val()
                },

                contentType: "application/json; charset=utf-8",
                dataFilter: function (data) { return data; },
                success: function(data) {
                    var items = data;
                    response(items);

                }
            });
        },

            });

    });

      </script>  
{% endblock %}